order:
  appId: com.tdx.tdxiMac
  defaultCheckBoxTitle: 刷新
  marketCode:
    SZ: 0
    SS: 1
  allQuantityTitle: 全部
  actionText: 下单
  orderInfo: $$$ {} ORDER $$$ ->  {}.{} -> Price = [{}]${}, Quantity = {} -> isAction = {}
  confirmAction:
    Ture: 确定
    False: 取消