order:
  appId: com.tdx.tdxiMac
  defaultCheckBoxTitle: 刷新
  marketCode:
    SZ: 0
    SS: 1
  allQuantityTitle: 全部
  actionText: 下单
  orderInfo: $$$ {} ORDER $$$ ->  {}.{} -> Price = [{}]${}, Quantity = {} -> isAction = {}
  confirmAction:
    Ture: 确定
    False: 取消
  histK:
    d: date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
    5: date,time,code,open,high,low,close,volume,amount,adjustflag
    60: date,time,code,open,high,low,close,volume,amount,adjustflag
